### ISSUE TITLE
C-PAC package as container wrapper

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1159]
- [x] Scope what's already done and what's left
- [x] Get a basic version running within the team
- [x] Look into PyPi hosting for package (if going that route)

**Comment by shnizzedy** [comment]
- 🚧 WIP in private repo: https://github.com/shnizzedy/cpac-python-package/commit/ae9c419cff0dfdfe91c22b62d5cb87e0a4f39137

**Comment by shnizzedy** [comment]
> Look into PyPi hosting for package

Pretty easy

1. update version & changelog
2. `python3 setup.py sdist bdist_wheel`
3. `python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*` (upload to test PyPI)
4. `pip install --index-url https://test.pypi.org/simple/ cpac` (install from test PyPI)
5. `twine upload dist/*` (uplead to real PyPI)

**Comment by shnizzedy** [comment]
I had to rename to [cpac_py](https://test.pypi.org/project/cpac-py) for test PyPI because I don't have rights to [cpac](https://test.pypi.org/project/CPAC). To install,

```sh
pip install --index-url https://test.pypi.org/simple/ cpac_py
```

but the commandline command is still `cpac`.

`cpac --help`, `cpac run --help` and `cpac utils --help` for options.
